/* ==================================================================
 *  Eniware Open sorce:Nikolai Manchev
 *  Apache License 2.0
 * ==================================================================
 */

package org.eniware.central.dao;

import org.eniware.domain.NetworkAssociation;

/**
 * DAO API for network association support.
 * 
 * @author matt
 * @version 1.0
 */
public interface NetworkAssociationDao {

	/**
	 * Get a network association for a confirmation code.
	 * 
	 * <p>
	 * The confirmation code would have been generated by SolarNet and passed to
	 * the user to confirm on their node.
	 * </p>
	 * 
	 * @param username
	 *        the username used when generating the confirmation code
	 * @param confirmationCode
	 *        the confirmation code
	 * @return the association, or <em>null</em> if none available
	 */
	NetworkAssociation getNetworkAssociationForConfirmationKey(String username, String confirmationCode);

}
