<style>
	/css/bootstrap.css
	/css/bootstrap-theme.css
	/css/global.css
	/css/edit-Edge.css
</style>
<script> 
	/js-lib/jquery-2.1.1.js
	/js-lib/jquery.form.js
	/js-lib/jquery.maphilight.js
	/js-lib/jquery.timezone-picker.js
	/js-lib/moment.js
	/js-lib/bootstrap.js
	/js/global.js
	/js/login.js
	/js/register.js
	/js/my-Edges.js
	/js/auth-tokens.js
	/js/alerts.js
	/js/billing.js
</script>
